import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import Sidebar, { SidebarItem } from "@/components/Layout/Sidebar";
import "./globals.css";
import { BarChart3, LayoutDashboard, Settings } from "lucide-react";
export const metadata: Metadata = {
  title: {
    default: "Projeto Teste",
    template: "%s | Gustavo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <main className="App">
          <Sidebar>
            <SidebarItem
              icon={<LayoutDashboard size={20} />}
              text="Dashboard"
            />
            <SidebarItem icon={<BarChart3 size={20} />} text="Products" />
            <hr className="my-3" />
            <SidebarItem icon={<Settings size={20} />} text="Settings" />
          </Sidebar>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
