import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
export const metadata: Metadata = {
  title: {
    default: "Projeto Teste",
    template: "%s | Gustavo",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
          <main className="App">
            <div className="w-full">{children}</div>
          </main>
      </body>
    </html>
  );
}
